spring:
  data:
    mongodb:
      uri: mongodb://arturo:123456Qwe@ds241570.mlab.com:41570/chefio-api-dev
      #uri: mongodb://java:123456Qwe@chefio-api-shard-00-00-nqiit.gcp.mongodb.net:27017,chefio-api-shard-00-01-nqiit.gcp.mongodb.net:27017,chefio-api-shard-00-02-nqiit.gcp.mongodb.net:27017/test?ssl=true&replicaSet=chefio-api-shard-0&authSource=admin&retryWrites=true&w=majority
      #database: test
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:
  level:
    ROOT: INFO
    org.springframework.data.mongodb: DEBUG
    
security:
  cors:
    origin: "capacitor://localhost, ionic://localhost, http://localhost, http://localhost:8080, http://localhost:8100"
    header: "*"
    method: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    credential: true