spring:
  data:
    mongodb:
      uri: mongodb://arturo:123456Qwe@ds211108-a0.mlab.com:11108,ds211108-a1.mlab.com:11108/chef-io-prod?replicaSet=rs-ds211108
      #uri: mongodb://arturo:123456Qwe@ds241570.mlab.com:41570/chefio-api-dev
  jackson:
    serialization:
      fail-on-empty-beans: false
      
logging:
  level:
    ROOT: INFO
    org.springframework.data.mongodb: ERROR
    
security:
  oauth2:
    resource:
      filterOrder: 3
  signingKey: HolaHola
  encodingStrength: 256
  securityRealm: HolaRealm
  jwt:
    clientId: clientId
    clientSecret: "clientSecret"
    grantType: password
    scopeRead: read
    scopeWrite: write
    resourceIds: oauth2-server
  cors:
    origin: "capacitor://localhost, ionic://localhost, http://localhost, http://localhost:8080, http://localhost:8100"
    header: "*"
    method: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    credential: true
    prodOrigin: "https://chefio-api-prod.herokuapp.com"